{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/artemaswang/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (7,10,18,19,20,21,23,30,31,32,33) have mixed types.Specify dtype option on import or set low_memory=False.\n",
      "  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n"
     ]
    }
   ],
   "source": [
    "art_test = pd.read_csv('Pandas Test File.csv') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>DataSource</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "      <th>Response</th>\n",
       "      <th>DataValueUnit</th>\n",
       "      <th>DataValueType</th>\n",
       "      <th>DataValue</th>\n",
       "      <th>...</th>\n",
       "      <th>LocationID</th>\n",
       "      <th>TopicID</th>\n",
       "      <th>QuestionID</th>\n",
       "      <th>DataValueTypeID</th>\n",
       "      <th>StratificationCategoryID1</th>\n",
       "      <th>StratificationID1</th>\n",
       "      <th>StratificationCategoryID2</th>\n",
       "      <th>StratificationID2</th>\n",
       "      <th>StratificationCategoryID3</th>\n",
       "      <th>StratificationID3</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>LocationAbbr</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>US</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>United States</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>16.9</td>\n",
       "      <td>...</td>\n",
       "      <td>59</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AL</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>Alabama</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>13</td>\n",
       "      <td>...</td>\n",
       "      <td>1</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AK</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>Alaska</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>18.2</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AZ</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>Arizona</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>15.6</td>\n",
       "      <td>...</td>\n",
       "      <td>4</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>AR</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>Arkansas</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>15</td>\n",
       "      <td>...</td>\n",
       "      <td>5</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>FL</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Florida</td>\n",
       "      <td>YRBSS</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>12</td>\n",
       "      <td>TOB</td>\n",
       "      <td>TOB2_1</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>HI</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Hawaii</td>\n",
       "      <td>YRBSS</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>15</td>\n",
       "      <td>TOB</td>\n",
       "      <td>TOB2_1</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VI</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Virgin Islands</td>\n",
       "      <td>YRBSS</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>78</td>\n",
       "      <td>TOB</td>\n",
       "      <td>TOB2_1</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>VT</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>YRBSS</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>50</td>\n",
       "      <td>TOB</td>\n",
       "      <td>TOB2_1</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>NM</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New Mexico</td>\n",
       "      <td>ACS 1-Year Estimates</td>\n",
       "      <td>Disability</td>\n",
       "      <td>Disability among adults aged &gt;= 65 years</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>35</td>\n",
       "      <td>DIS</td>\n",
       "      <td>DIS1_0</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>RACE</td>\n",
       "      <td>BLK</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>519718 rows × 33 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "              YearStart  YearEnd    LocationDesc            DataSource  \\\n",
       "LocationAbbr                                                             \n",
       "US                 2016     2016   United States                 BRFSS   \n",
       "AL                 2016     2016         Alabama                 BRFSS   \n",
       "AK                 2016     2016          Alaska                 BRFSS   \n",
       "AZ                 2016     2016         Arizona                 BRFSS   \n",
       "AR                 2016     2016        Arkansas                 BRFSS   \n",
       "...                 ...      ...             ...                   ...   \n",
       "FL                 2015     2015         Florida                 YRBSS   \n",
       "HI                 2015     2015          Hawaii                 YRBSS   \n",
       "VI                 2015     2015  Virgin Islands                 YRBSS   \n",
       "VT                 2015     2015         Vermont                 YRBSS   \n",
       "NM                 2013     2013      New Mexico  ACS 1-Year Estimates   \n",
       "\n",
       "                   Topic                                           Question  \\\n",
       "LocationAbbr                                                                  \n",
       "US               Alcohol  Binge drinking prevalence among adults aged >=...   \n",
       "AL               Alcohol  Binge drinking prevalence among adults aged >=...   \n",
       "AK               Alcohol  Binge drinking prevalence among adults aged >=...   \n",
       "AZ               Alcohol  Binge drinking prevalence among adults aged >=...   \n",
       "AR               Alcohol  Binge drinking prevalence among adults aged >=...   \n",
       "...                  ...                                                ...   \n",
       "FL               Tobacco          Current smokeless tobacco use among youth   \n",
       "HI               Tobacco          Current smokeless tobacco use among youth   \n",
       "VI               Tobacco          Current smokeless tobacco use among youth   \n",
       "VT               Tobacco          Current smokeless tobacco use among youth   \n",
       "NM            Disability           Disability among adults aged >= 65 years   \n",
       "\n",
       "             Response DataValueUnit     DataValueType DataValue  ...  \\\n",
       "LocationAbbr                                                     ...   \n",
       "US                NaN             %  Crude Prevalence      16.9  ...   \n",
       "AL                NaN             %  Crude Prevalence        13  ...   \n",
       "AK                NaN             %  Crude Prevalence      18.2  ...   \n",
       "AZ                NaN             %  Crude Prevalence      15.6  ...   \n",
       "AR                NaN             %  Crude Prevalence        15  ...   \n",
       "...               ...           ...               ...       ...  ...   \n",
       "FL                NaN             %  Crude Prevalence       NaN  ...   \n",
       "HI                NaN             %  Crude Prevalence       NaN  ...   \n",
       "VI                NaN             %  Crude Prevalence       NaN  ...   \n",
       "VT                NaN             %  Crude Prevalence       NaN  ...   \n",
       "NM                NaN             %  Crude Prevalence       NaN  ...   \n",
       "\n",
       "              LocationID TopicID QuestionID  DataValueTypeID  \\\n",
       "LocationAbbr                                                   \n",
       "US                    59     ALC     ALC2_2          CRDPREV   \n",
       "AL                     1     ALC     ALC2_2          CRDPREV   \n",
       "AK                     2     ALC     ALC2_2          CRDPREV   \n",
       "AZ                     4     ALC     ALC2_2          CRDPREV   \n",
       "AR                     5     ALC     ALC2_2          CRDPREV   \n",
       "...                  ...     ...        ...              ...   \n",
       "FL                    12     TOB     TOB2_1          CRDPREV   \n",
       "HI                    15     TOB     TOB2_1          CRDPREV   \n",
       "VI                    78     TOB     TOB2_1          CRDPREV   \n",
       "VT                    50     TOB     TOB2_1          CRDPREV   \n",
       "NM                    35     DIS     DIS1_0          CRDPREV   \n",
       "\n",
       "              StratificationCategoryID1 StratificationID1  \\\n",
       "LocationAbbr                                                \n",
       "US                              OVERALL               OVR   \n",
       "AL                              OVERALL               OVR   \n",
       "AK                              OVERALL               OVR   \n",
       "AZ                              OVERALL               OVR   \n",
       "AR                              OVERALL               OVR   \n",
       "...                                 ...               ...   \n",
       "FL                              OVERALL               OVR   \n",
       "HI                              OVERALL               OVR   \n",
       "VI                              OVERALL               OVR   \n",
       "VT                              OVERALL               OVR   \n",
       "NM                                 RACE               BLK   \n",
       "\n",
       "             StratificationCategoryID2 StratificationID2  \\\n",
       "LocationAbbr                                               \n",
       "US                                 NaN               NaN   \n",
       "AL                                 NaN               NaN   \n",
       "AK                                 NaN               NaN   \n",
       "AZ                                 NaN               NaN   \n",
       "AR                                 NaN               NaN   \n",
       "...                                ...               ...   \n",
       "FL                                 NaN               NaN   \n",
       "HI                                 NaN               NaN   \n",
       "VI                                 NaN               NaN   \n",
       "VT                                 NaN               NaN   \n",
       "NM                                 NaN               NaN   \n",
       "\n",
       "             StratificationCategoryID3 StratificationID3  \n",
       "LocationAbbr                                              \n",
       "US                                 NaN               NaN  \n",
       "AL                                 NaN               NaN  \n",
       "AK                                 NaN               NaN  \n",
       "AZ                                 NaN               NaN  \n",
       "AR                                 NaN               NaN  \n",
       "...                                ...               ...  \n",
       "FL                                 NaN               NaN  \n",
       "HI                                 NaN               NaN  \n",
       "VI                                 NaN               NaN  \n",
       "VT                                 NaN               NaN  \n",
       "NM                                 NaN               NaN  \n",
       "\n",
       "[519718 rows x 33 columns]"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "art_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [],
   "source": [
    "art_test['LocationAbbr'] = art_test['LocationAbbr'].astype(object)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 519718 entries, 0 to 519717\n",
      "Data columns (total 34 columns):\n",
      " #   Column                     Non-Null Count   Dtype  \n",
      "---  ------                     --------------   -----  \n",
      " 0   YearStart                  519718 non-null  int64  \n",
      " 1   YearEnd                    519718 non-null  int64  \n",
      " 2   LocationAbbr               519718 non-null  object \n",
      " 3   LocationDesc               519718 non-null  object \n",
      " 4   DataSource                 519718 non-null  object \n",
      " 5   Topic                      519718 non-null  object \n",
      " 6   Question                   519718 non-null  object \n",
      " 7   Response                   79188 non-null   object \n",
      " 8   DataValueUnit              476046 non-null  object \n",
      " 9   DataValueType              519718 non-null  object \n",
      " 10  DataValue                  374564 non-null  object \n",
      " 11  DataValueAlt               350335 non-null  float64\n",
      " 12  DataValueFootnoteSymbol    227318 non-null  object \n",
      " 13  DatavalueFootnote          227152 non-null  object \n",
      " 14  LowConfidenceLimit         311062 non-null  float64\n",
      " 15  HighConfidenceLimit        311062 non-null  float64\n",
      " 16  StratificationCategory1    519718 non-null  object \n",
      " 17  Stratification1            519718 non-null  object \n",
      " 18  StratificationCategory2    79188 non-null   object \n",
      " 19  Stratification2            79188 non-null   object \n",
      " 20  StratificationCategory3    79188 non-null   object \n",
      " 21  Stratification3            79188 non-null   object \n",
      " 22  GeoLocation                516115 non-null  object \n",
      " 23  ResponseID                 79176 non-null   object \n",
      " 24  LocationID                 519718 non-null  int64  \n",
      " 25  TopicID                    519718 non-null  object \n",
      " 26  QuestionID                 519718 non-null  object \n",
      " 27  DataValueTypeID            519718 non-null  object \n",
      " 28  StratificationCategoryID1  519718 non-null  object \n",
      " 29  StratificationID1          519718 non-null  object \n",
      " 30  StratificationCategoryID2  79189 non-null   object \n",
      " 31  StratificationID2          79189 non-null   object \n",
      " 32  StratificationCategoryID3  79188 non-null   object \n",
      " 33  StratificationID3          79188 non-null   object \n",
      "dtypes: float64(3), int64(3), object(28)\n",
      "memory usage: 134.8+ MB\n"
     ]
    }
   ],
   "source": [
    "art_test.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationAbbr</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>DataSource</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "      <th>Response</th>\n",
       "      <th>DataValueUnit</th>\n",
       "      <th>DataValueType</th>\n",
       "      <th>...</th>\n",
       "      <th>LocationID</th>\n",
       "      <th>TopicID</th>\n",
       "      <th>QuestionID</th>\n",
       "      <th>DataValueTypeID</th>\n",
       "      <th>StratificationCategoryID1</th>\n",
       "      <th>StratificationID1</th>\n",
       "      <th>StratificationCategoryID2</th>\n",
       "      <th>StratificationID2</th>\n",
       "      <th>StratificationCategoryID3</th>\n",
       "      <th>StratificationID3</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>US</td>\n",
       "      <td>United States</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>...</td>\n",
       "      <td>59</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>AL</td>\n",
       "      <td>Alabama</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>...</td>\n",
       "      <td>1</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>AK</td>\n",
       "      <td>Alaska</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>...</td>\n",
       "      <td>2</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>AZ</td>\n",
       "      <td>Arizona</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>...</td>\n",
       "      <td>4</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2016</td>\n",
       "      <td>2016</td>\n",
       "      <td>AR</td>\n",
       "      <td>Arkansas</td>\n",
       "      <td>BRFSS</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Binge drinking prevalence among adults aged &gt;=...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>%</td>\n",
       "      <td>Crude Prevalence</td>\n",
       "      <td>...</td>\n",
       "      <td>5</td>\n",
       "      <td>ALC</td>\n",
       "      <td>ALC2_2</td>\n",
       "      <td>CRDPREV</td>\n",
       "      <td>OVERALL</td>\n",
       "      <td>OVR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 34 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   YearStart  YearEnd LocationAbbr   LocationDesc DataSource    Topic  \\\n",
       "0       2016     2016           US  United States      BRFSS  Alcohol   \n",
       "1       2016     2016           AL        Alabama      BRFSS  Alcohol   \n",
       "2       2016     2016           AK         Alaska      BRFSS  Alcohol   \n",
       "3       2016     2016           AZ        Arizona      BRFSS  Alcohol   \n",
       "4       2016     2016           AR       Arkansas      BRFSS  Alcohol   \n",
       "\n",
       "                                            Question Response DataValueUnit  \\\n",
       "0  Binge drinking prevalence among adults aged >=...      NaN             %   \n",
       "1  Binge drinking prevalence among adults aged >=...      NaN             %   \n",
       "2  Binge drinking prevalence among adults aged >=...      NaN             %   \n",
       "3  Binge drinking prevalence among adults aged >=...      NaN             %   \n",
       "4  Binge drinking prevalence among adults aged >=...      NaN             %   \n",
       "\n",
       "      DataValueType  ... LocationID  TopicID QuestionID DataValueTypeID  \\\n",
       "0  Crude Prevalence  ...         59      ALC     ALC2_2         CRDPREV   \n",
       "1  Crude Prevalence  ...          1      ALC     ALC2_2         CRDPREV   \n",
       "2  Crude Prevalence  ...          2      ALC     ALC2_2         CRDPREV   \n",
       "3  Crude Prevalence  ...          4      ALC     ALC2_2         CRDPREV   \n",
       "4  Crude Prevalence  ...          5      ALC     ALC2_2         CRDPREV   \n",
       "\n",
       "   StratificationCategoryID1  StratificationID1 StratificationCategoryID2  \\\n",
       "0                    OVERALL                OVR                       NaN   \n",
       "1                    OVERALL                OVR                       NaN   \n",
       "2                    OVERALL                OVR                       NaN   \n",
       "3                    OVERALL                OVR                       NaN   \n",
       "4                    OVERALL                OVR                       NaN   \n",
       "\n",
       "  StratificationID2 StratificationCategoryID3 StratificationID3  \n",
       "0               NaN                       NaN               NaN  \n",
       "1               NaN                       NaN               NaN  \n",
       "2               NaN                       NaN               NaN  \n",
       "3               NaN                       NaN               NaN  \n",
       "4               NaN                       NaN               NaN  \n",
       "\n",
       "[5 rows x 34 columns]"
      ]
     },
     "execution_count": 58,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "art_test.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "selected_columns = art_test[['YearStart','YearEnd','LocationDesc','Topic','Question']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>519713</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Florida</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519714</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Hawaii</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519715</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Virgin Islands</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519716</th>\n",
       "      <td>2015</td>\n",
       "      <td>2015</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Current smokeless tobacco use among youth</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519717</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New Mexico</td>\n",
       "      <td>Disability</td>\n",
       "      <td>Disability among adults aged &gt;= 65 years</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        YearStart  YearEnd    LocationDesc       Topic  \\\n",
       "519713       2015     2015         Florida     Tobacco   \n",
       "519714       2015     2015          Hawaii     Tobacco   \n",
       "519715       2015     2015  Virgin Islands     Tobacco   \n",
       "519716       2015     2015         Vermont     Tobacco   \n",
       "519717       2013     2013      New Mexico  Disability   \n",
       "\n",
       "                                         Question  \n",
       "519713  Current smokeless tobacco use among youth  \n",
       "519714  Current smokeless tobacco use among youth  \n",
       "519715  Current smokeless tobacco use among youth  \n",
       "519716  Current smokeless tobacco use among youth  \n",
       "519717   Disability among adults aged >= 65 years  "
      ]
     },
     "execution_count": 67,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "selected_columns.tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [],
   "source": [
    "selected_years = selected_columns[selected_columns['YearEnd'] == 2013] "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>395658</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Pneumococcal vaccination among noninstitutiona...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>395659</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Pneumococcal vaccination among noninstitutiona...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>395660</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Pneumococcal vaccination among noninstitutiona...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>395661</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>North Carolina</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Pneumococcal vaccination among noninstitutiona...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>395662</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>North Dakota</td>\n",
       "      <td>Tobacco</td>\n",
       "      <td>Pneumococcal vaccination among noninstitutiona...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        YearStart  YearEnd    LocationDesc    Topic  \\\n",
       "395658       2013     2013  North Carolina  Tobacco   \n",
       "395659       2013     2013  North Carolina  Tobacco   \n",
       "395660       2013     2013  North Carolina  Tobacco   \n",
       "395661       2013     2013  North Carolina  Tobacco   \n",
       "395662       2013     2013    North Dakota  Tobacco   \n",
       "\n",
       "                                                 Question  \n",
       "395658  Pneumococcal vaccination among noninstitutiona...  \n",
       "395659  Pneumococcal vaccination among noninstitutiona...  \n",
       "395660  Pneumococcal vaccination among noninstitutiona...  \n",
       "395661  Pneumococcal vaccination among noninstitutiona...  \n",
       "395662  Pneumococcal vaccination among noninstitutiona...  "
      ]
     },
     "execution_count": 70,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "selected_years.iloc[80000:80005,]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>124723</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Asthma</td>\n",
       "      <td>Hospitalizations for asthma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124724</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Asthma</td>\n",
       "      <td>Hospitalizations for asthma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124725</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Asthma</td>\n",
       "      <td>Hospitalizations for asthma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124726</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Asthma</td>\n",
       "      <td>Hospitalizations for asthma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>124727</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Asthma</td>\n",
       "      <td>Hospitalizations for asthma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>518146</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Overarching Conditions</td>\n",
       "      <td>High school completion among adults aged 18-24...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>518201</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Overarching Conditions</td>\n",
       "      <td>High school completion among adults aged 18-24...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519165</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Disability</td>\n",
       "      <td>Disability among adults aged &gt;= 65 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519166</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Disability</td>\n",
       "      <td>Disability among adults aged &gt;= 65 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>519167</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>Vermont</td>\n",
       "      <td>Disability</td>\n",
       "      <td>Disability among adults aged &gt;= 65 years</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1892 rows × 5 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        YearStart  YearEnd LocationDesc                   Topic  \\\n",
       "124723       2013     2013      Vermont                  Asthma   \n",
       "124724       2013     2013      Vermont                  Asthma   \n",
       "124725       2013     2013      Vermont                  Asthma   \n",
       "124726       2013     2013      Vermont                  Asthma   \n",
       "124727       2013     2013      Vermont                  Asthma   \n",
       "...           ...      ...          ...                     ...   \n",
       "518146       2013     2013      Vermont  Overarching Conditions   \n",
       "518201       2013     2013      Vermont  Overarching Conditions   \n",
       "519165       2013     2013      Vermont              Disability   \n",
       "519166       2013     2013      Vermont              Disability   \n",
       "519167       2013     2013      Vermont              Disability   \n",
       "\n",
       "                                                 Question  \n",
       "124723                        Hospitalizations for asthma  \n",
       "124724                        Hospitalizations for asthma  \n",
       "124725                        Hospitalizations for asthma  \n",
       "124726                        Hospitalizations for asthma  \n",
       "124727                        Hospitalizations for asthma  \n",
       "...                                                   ...  \n",
       "518146  High school completion among adults aged 18-24...  \n",
       "518201  High school completion among adults aged 18-24...  \n",
       "519165           Disability among adults aged >= 65 years  \n",
       "519166           Disability among adults aged >= 65 years  \n",
       "519167           Disability among adults aged >= 65 years  \n",
       "\n",
       "[1892 rows x 5 columns]"
      ]
     },
     "execution_count": 74,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "selected_years.loc[selected_years['Topic'] == 'Asthma']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [],
   "source": [
    "# selets two conditions\n",
    "artemas = selected_columns.loc[(selected_columns['YearStart'] == 2015) & \n",
    "                               (selected_columns['LocationDesc'] == 'California') &\n",
    "                               (selected_columns['Topic'] == 'Asthma') | \n",
    "                               (selected_columns['YearStart'] == 2013) & \n",
    "                               (selected_columns['LocationDesc'] == 'New York') &\n",
    "                               (selected_columns['Topic'] == 'Alcohol')] "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YearStart</th>\n",
       "      <th>YearEnd</th>\n",
       "      <th>LocationDesc</th>\n",
       "      <th>Topic</th>\n",
       "      <th>Question</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>512078</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New York</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Heavy drinking among women aged 18-44 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>512133</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New York</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Heavy drinking among women aged 18-44 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>512187</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New York</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Heavy drinking among women aged 18-44 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>512243</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New York</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Heavy drinking among women aged 18-44 years</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>512297</th>\n",
       "      <td>2013</td>\n",
       "      <td>2013</td>\n",
       "      <td>New York</td>\n",
       "      <td>Alcohol</td>\n",
       "      <td>Heavy drinking among women aged 18-44 years</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        YearStart  YearEnd LocationDesc    Topic  \\\n",
       "512078       2013     2013     New York  Alcohol   \n",
       "512133       2013     2013     New York  Alcohol   \n",
       "512187       2013     2013     New York  Alcohol   \n",
       "512243       2013     2013     New York  Alcohol   \n",
       "512297       2013     2013     New York  Alcohol   \n",
       "\n",
       "                                           Question  \n",
       "512078  Heavy drinking among women aged 18-44 years  \n",
       "512133  Heavy drinking among women aged 18-44 years  \n",
       "512187  Heavy drinking among women aged 18-44 years  \n",
       "512243  Heavy drinking among women aged 18-44 years  \n",
       "512297  Heavy drinking among women aged 18-44 years  "
      ]
     },
     "execution_count": 105,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "artemas.tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
